name: Pipeline 1 - CI portalWeb

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Executar checkout
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # 2 e 3. Executar setup-node e cache npm
      - name: Configurar Node.js e habilitar Cache
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Substitua pela versão que seu grupo usa (ex: 18, 20, 22)
          cache: 'npm'

      # 4. Executar npm install
      - name: Instalar dependências
        run: npm install

      # 5. Executar eslint
      - name: Checar código com ESLint
        run: npx eslint .

      # 6. Executar prettier
      - name: Checar formatação com Prettier
        run: npx prettier --check .

      # 7. Executar build
      - name: Build do projeto
        run: npm run build